version: "3.9"

services:
  web:
    image: rosudaivdg/stock_price_api_dev
    ports:
      - "5000:5000"
    environment:
      BEARER_TOKEN_FILE: /run/secrets/bearer_token
      FINNHUB_API_TOKEN_FILE: /run/secrets/finnhub_api_token
    secrets:
      - bearer_token
      - finnhub_api_token

secrets:
  bearer_token:
    file: secrets/bearer_token
  finnhub_api_token:
    file: secrets/finnhub_api_token
